---
version: 2
jobs:
  node-latest: &test
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - run: |
          set +e
          wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash
          export NVM_DIR="/opt/circleci/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      - run: |
          node -v
      - run: |
          nvm install v12
          nvm install v10.16.3
          node -v
          nvm alias default v10.16.3
      - run:
          name: Install dependencies
          command: yarn
      - run: ./bin/run --version
      - run: ./bin/run --help
      - run:
          name: Testing
          command: yarn test
      - run:
          name: Upload code coverage to codecov
          command: yarn cov
      - run:
          name: Build binaries
          command: yarn run make-binaries
      - run: cd dist && find . -type f -print0 | xargs -0 shasum -a 256 > ../shasum.256.asc && cd .. && cp shasum.256.asc dist/
      - run: zip -r qrl-cli-macos.zip dist/macos
      - run: zip -r qrl-cli-win.zip dist/win
      - run: zip -r qrl-cli-linux.zip dist/linux
      - run:
          name: "Publish Release on GitHub"
          command: nvm use v12 && npx semantic-release

  cache:
    <<: *test
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
          paths:
            - ~/cli/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn

workflows:
  version: 2
  "qrl-cli":
    jobs:
      - node-latest
      - cache:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
